#!/bin/sh

echo "RS"

refresh="pkill -RTMIN+10 i3blocks"

case $BLOCK_BUTTON in
	
	1) notify-send "Radio ON!" ;  $refresh ;;
	#mplayer "http://161.53.122.184:8000/AAC128.aac" 
	3) pkill mplayer ; notify-send "Radio OFF!" ; $refresh ;; 
esac
